import { normalizeMailbox } from "../../mail/shared";
import { normalizeDomain } from "../../security";
import { recordValue } from "../../worker/shared";
import { buildProviderReportNarrative, normalizeObservedUrlForDomain } from "../report_payload";
import { NETCRAFT_PROVIDER } from "./definition";

export type NetcraftSubmissionPayload = {
	adapter: "netcraft_report_urls_v3";
	providerNarrativeVersion: 1;
	definition: {
		version: string;
		contentHash: string;
	};
	target: {
		normalizedTarget: string;
		observedUrls: string[];
	};
	report: {
		reporterEmail: string;
		reason: string;
	};
};

export type NetcraftReportUrlsBody = {
	email: string;
	reason: string;
	urls: Array<{ url: string }>;
};

function sameStrings(left: readonly string[], right: readonly string[]): boolean {
	return left.length === right.length && left.every((value, index) => value === right[index]);
}

function normalizeObservedUrls(values: unknown, target: string): string[] | undefined {
	if (!Array.isArray(values) || values.length === 0 || values.length > NETCRAFT_PROVIDER.maximumUrlsPerSubmission) return undefined;
	const normalized: string[] = [];
	for (const value of values) {
		if (typeof value !== "string") return undefined;
		const url = normalizeObservedUrlForDomain(value, target);
		if (!url) return undefined;
		if (!normalized.includes(url)) normalized.push(url);
	}
	return normalized;
}

/** Build the concise report narrative accepted by Netcraft's v3 URL endpoint. */
export function makeNetcraftReason(params: {
	target?: string;
	observedUrls?: readonly string[];
	description: string;
	legalBrandUrl?: string;
}): string | undefined {
	return buildProviderReportNarrative({
		provider: "netcraft",
		target: params.target,
		observedUrls: params.observedUrls,
		description: params.description,
		...(params.legalBrandUrl !== undefined ? { legalBrandUrl: params.legalBrandUrl } : {}),
		maximumLength: NETCRAFT_PROVIDER.maximumReasonLength,
	});
}

/** Create Netcraft's durable, secret-free payload before the network boundary. */
export function buildNetcraftSubmissionPayload(params: {
	target: string;
	observedUrls: readonly string[];
	description: string;
	legalBrandUrl?: string;
	reporterEmail: string;
}): NetcraftSubmissionPayload | undefined {
	const normalizedTarget = normalizeDomain(params.target);
	const observedUrls = normalizedTarget ? normalizeObservedUrls(params.observedUrls, normalizedTarget) : undefined;
	const reporterEmail = normalizeMailbox(params.reporterEmail);
	const reason = makeNetcraftReason({
		target: normalizedTarget,
		observedUrls,
		description: params.description,
		...(params.legalBrandUrl === undefined ? {} : { legalBrandUrl: params.legalBrandUrl }),
	});
	if (!normalizedTarget || !observedUrls || !reporterEmail || !reason) return undefined;

	return {
		adapter: "netcraft_report_urls_v3",
		providerNarrativeVersion: 1,
		definition: { version: NETCRAFT_PROVIDER.version, contentHash: NETCRAFT_PROVIDER.contentHash },
		target: { normalizedTarget, observedUrls },
		report: { reporterEmail, reason },
	};
}

/** Read only a payload generated by the reviewed Netcraft adapter. */
export function storedNetcraftSubmissionPayload(value: unknown): NetcraftSubmissionPayload | undefined {
	const payload = recordValue(value);
	const definition = payload && recordValue(payload.definition);
	const target = payload && recordValue(payload.target);
	const report = payload && recordValue(payload.report);
	if (!payload || payload.adapter !== "netcraft_report_urls_v3" || payload.providerNarrativeVersion !== 1
		|| !definition || definition.version !== NETCRAFT_PROVIDER.version || definition.contentHash !== NETCRAFT_PROVIDER.contentHash
		|| !target || typeof target.normalizedTarget !== "string"
		|| !report || typeof report.reporterEmail !== "string" || typeof report.reason !== "string"
		|| report.reason.length === 0 || report.reason.length > NETCRAFT_PROVIDER.maximumReasonLength) {
		return undefined;
	}
	const normalizedTarget = normalizeDomain(target.normalizedTarget);
	const observedUrls = normalizedTarget ? normalizeObservedUrls(target.observedUrls, normalizedTarget) : undefined;
	const reporterEmail = normalizeMailbox(report.reporterEmail);
	if (!normalizedTarget || normalizedTarget !== target.normalizedTarget || !observedUrls || !Array.isArray(target.observedUrls)
		|| !sameStrings(observedUrls, target.observedUrls) || !reporterEmail || reporterEmail !== report.reporterEmail) {
		return undefined;
	}
	return {
		adapter: "netcraft_report_urls_v3",
		providerNarrativeVersion: 1,
		definition: { version: NETCRAFT_PROVIDER.version, contentHash: NETCRAFT_PROVIDER.contentHash },
		target: { normalizedTarget, observedUrls },
		report: { reporterEmail, reason: report.reason },
	};
}

/** Transform the validated durable payload into Netcraft's documented JSON body. */
export function buildNetcraftReportUrlsBody(payload: NetcraftSubmissionPayload): NetcraftReportUrlsBody {
	return {
		email: payload.report.reporterEmail,
		reason: payload.report.reason,
		urls: payload.target.observedUrls.map((url) => ({ url })),
	};
}
